### ISSUE TITLE
Typo in run_drq example.

### ISSUE THREAD

**Issue by akbir** [ethanluoyc/magi#62]
Line reference:
https://github.com/ethanluoyc/magi/blob/cff26ddb87165bb6e19796dc77521e3191afcffc/magi/examples/run_drq.py#L32

Default value should be "10000"

**Comment by ethanluoyc** [comment]
The value I used here is chosen a bit arbitrarily, something that's smaller than 1M (that's probably a bit large for some people's machines, is there a reason that you are recommending 10000 instead of the value given here?

**Comment by akbir** [comment]
flags can not parse `100_000`
